name: Deploy Testnet

on:
  push:
    branches:
      - 'master'
    paths:
      - 'contracts/*'
      - 'migrations/*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubunutu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Deploy to Test Net
        run: ls


