name: Publish Package

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths: 
      - '!contracts/*'
      - '!migrations/*'
      - 'package/*'

jobs:

  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
          cache: npm

      - name: Download Contract ABIs Artifact 
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: Deploy.yml
          workflow_conclusion: success
          branch: master
          name: contract-abis
          path: build

      - name: Publish Package
        run: npm run-script publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

