# This is a basic workflow to help you get started with Actions

name: Solidity CI

# Controls when the workflow will run
on:
  push:
    paths: 
      - '**/*.sol'
      - 'test/**.test.js'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v2.3.0
        with:
          node-version: 16.x
          cache: npm

      - name: Install project dependencies
        run: npm install

      - name: Launch truffle development chain
        run: npm run-script dev; sleep 6

      - name: Run tests
        run: npm run-script test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
        
      - name: Install project dependencies
        run: npm install

      - name: Run Linter
        run: npm run-script lint
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v2.3.0
        with:
          node-version: 16.x
          cache: npm

      - name: Install project dependencies
        run: npm install

      - name: Run Code Coverage Reporter
        run: npm run-script coverage
